### ISSUE TITLE
buttonDown, buttonUp are called every frame, even when no buttons are being pressed

### ISSUE THREAD

**Issue by bartek1009x** [libgdx/gdx-controllers#51]
I'm testing my game with a Nintendo Switch Pro controller on Windows. The controller works perfectly fine.

I have a class that implements ControllerListener, and of course in the main class I add the listener through `Controllers.addListener();`.

In this function:
```java
    @Override
    public boolean buttonDown(Controller controller, int i) {
        System.out.println("Button down: " + controller.getButton(i));

        if (i == controller.getMapping().buttonA) {
            processEnter();
        }

        return true;
    }
```

"Button down: true" is printed and the processEnter function gets called every frame, despite none of the buttons being pressed. I checked the buttonUp function and it acted the same way.

However, I tried downgrading the gdx-controllers version a few times, and it seems that this is a problem in 2.2.4, 2.2.3, and 2.2.2. In version 2.2.1, everything works properly and the buttonDown and buttonUp functions are called when I actually press a button, so this bug must have been introduced in 2.2.2.

**Comment by MrStahlfelge** [comment]
Probably this is caused by SDL version which ships with Jamepad and was changed from 2.2.1 to 2.2.2: https://github.com/libgdx/gdx-controllers/wiki/Compatibility

You can downgrade Jamepad to 2.0.14.1 or try version 2.30.0.0, or you can try behaviour with the SDL3 PR branch in this repo.

**Comment by bartek1009x** [comment]
```groovy
implementation("com.badlogicgames.jamepad:jamepad:2.0.14.1") {
  exclude group: 'com.badlogicgames.gdx', module: 'gdx-jnigen-loader'
}
implementation "com.badlogicgames.gdx-controllers:gdx-controllers-desktop:2.2.4"
```

I hope I'm doing this correctly. If I am, neither 2.0.14.1 or 2.30.0.0 fix the issue (on 2.2.4). I guess I'll just stick to 2.2.1 for now.

**Comment by MrStahlfelge** [comment]
This way, you can only upgrade, so using 2.0.14.1 on 2.2.4 did not work. What you can try is vice versa, add 2.30.0.0 to 2.2.1 and check if the error is there. Then we now exactly if Jamepad/SDL or a gdx-controllers change is causing the problem.

**Comment by bartek1009x** [comment]
Ah, I see.
Well, when I have gdx-controllers 2.2.1, updating Jamepad to anything after 2.0.20.0 crashes the game on startup with this error:

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.JamepadControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:119)
	at com.badlogic.gdx.controllers.Controllers.addListener(Controllers.java:65)
	at com.bartek1009x.Main.create(Main.java:118)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:464)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:402)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:181)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:153)
	at com.bartek1009x.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:22)
	at com.bartek1009x.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:18)
Caused by: java.lang.NoSuchMethodError: 'void com.studiohartman.jamepad.ControllerManager.update()'
	at com.badlogic.gdx.controllers.desktop.support.JamepadControllerMonitor.run(JamepadControllerMonitor.java:23)
	at com.badlogic.gdx.controllers.desktop.JamepadControllerManager.<init>(JamepadControllerManager.java:38)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:79)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:194)
	at java.base/java.lang.Class.newInstance(Class.java:711)
	at com.badlogic.gdx.utils.reflect.ClassReflection.newInstance(ClassReflection.java:93)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:117)
	... 8 more
```

When I update Jamepad to 2.0.20.0, the latest version that doesn't crash with gdx-controllers 2.2.1, I am experiencing the same input issue. 2.0.14.2 seems to be the last Jamepad version that works properly.

(I've tried the versions avilable on [the releases page for Jamepad](https://github.com/libgdx/Jamepad/releases))

**Comment by MrStahlfelge** [comment]
Okay, this might be an issue with the controller and SDL. Did you try the SDL3 PR branch btw?
What you can also do: JamepadController#updateButtonsState calls the listeners and should do that only when there is a change. It is called every frame so something is not working in the logic here. You stated that buttonDown as well as button up is called every frame - that is not possible by the logic, it must happen every second frame, but that nearly looks the same: Check why it does not recognize that there is no change between the calls to the method.

**Comment by bartek1009x** [comment]
I don't really know how I can test the SDL3 PR branch. I tried to copy it locally and build it as a jar then include in my game, but it caused a lot of errors and every time I fixed one, another one appeared. Perhaps it could be caused by the mismatch between LWJGL versions in the PR branch (4.0.0-SNAPSHOT) and my game's version (3.3.3) that comes with LibGDX 1.13.1. I'm unable to resolve that, so I can't run the SDL3 branch, sorry.

Regarding buttonDown and buttonUp - it could be every second frame, I honestly haven't checked if it's actually every frame. The prints in the console were appearing so fast I just assumed it must be every frame.

Also, after further testing, I have to reclarify that buttonDown and buttonUp called every two frames isn't the only issue. It's actually way more complicated.
I switched to gdx-controllers 2.2.4 and my controller wasn't being detected at all, despite plugging and unplugging. I tried many times and I couldn't get the game to react to the controller getting connected. Then I launched a compltely different unrelated Steam game to check if the controller worked properly, and it worked in that game. Then I came back to my game and it started reacting to the controller getting plugged in, and the issue where buttonDown and buttonUp would get called constantly for all buttons started happening again. I know that what I have just written might be a bit complicated so I recorded footage of it:
https://www.youtube.com/watch?v=-Y0h8iQUGbM

**Comment by Yontipon** [comment]
> Well, when I have gdx-controllers 2.2.1, updating Jamepad to anything after 2.0.20.0 crashes the game on startup with this error:

This is happening because I changed the return type of `update()` from `void` to `boolean`. I hadn't considered mixing the old and new versions, and I wouldn't have thought it would cause a problem, since the method signature is the same, and the return value could be safely ignored, but I guess java doesn't like that. We could consider doing something about that, but it probably deserves its own issue.

As for this issue, my first guess would be that the database of mappings doesn't have an entry for your specific controller. It's supposed to fall back on a default mapping in that case, but I suspect this hasn't worked for a while. If you find the controller's GUID, you could check if the database has an entry for it on your platform, and manually add one locally.

The constant inputs might be the result of garbage data left behind by the previous game, which wouldn't be a problem if we were getting the controller connected properly.

Some other ideas:
Do you have another type of controller you can test with?
Do you have another computer or operating system to test on?
You could try running the test program that comes with gdx-controllers.

**Comment by bartek1009x** [comment]
> As for this issue, my first guess would be that the database of mappings doesn't have an entry for your specific controller.

I checked the DB and it seems they do have mappings for the Nintendo Switch Pro controller on all platforms, including Windows which I am using.

<img width="1919" height="897" alt="Image" src="https://github.com/user-attachments/assets/ccff7cb9-3c53-4f0b-94b8-c869b65bd9ae" />

Sadly I have no other controller I could test the game on. I can however check it on another computer later.

**Comment by bartek1009x** [comment]
I haven't been able to check it on another computer yet, but I tried running the test program in gdx-controllers. Here's what I got:

https://github.com/user-attachments/assets/16d18f77-77e1-4ad2-ad09-905978294711

The input for all buttons started the moment i plugged in my controller (with the test app running already).

**Comment by bartek1009x** [comment]
I have just dual booted Linux and tested the game on it. Everything seems to be working fine with the controller input on Linux, even with gdx-controllers 2.2.4. Must be a Windows specific issue then?

**Comment by MrStahlfelge** [comment]
Probably this specific controller on Windows, as there is no general problem with the lib on Windows.

**Comment by Yontipon** [comment]
I found the following line in the SDL 2.30.6 update notes:

> Improved detection of Nintendo Switch Pro controller report mode

Sounds like it could be related to this issue. I believe we've only tried up to 2.30.0.
